name: Run Tests
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    env:
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      VITE_COVERAGE: ${{ vars.VITE_COVERAGE }}
      NODE_ENV: ${{ vars.NODE_ENV }}
      REDIS_PORT: ${{ vars.REDIS_PORT }}
      REDIS_HOST: ${{ vars.REDIS_HOST }}
      DB_HOST: ${{ vars.DB_HOST }}
      DB_USER: ${{ vars.DB_USER }}
      DB_NAME: ${{ vars.DB_NAME }}
      DB_PORT: ${{ vars.DB_PORT }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - run: ./scripts/create-test-env.sh
      - run: cp .env.test .env
      - run: npx svelte-kit sync
      - run: npm run check
      - run: npm run lint
      # - run: npx playwright install
      - run: npm run test:unit
